train:
  num_epochs: 5
  accum_iter: 10
  batch_size: 8
  base_lr: 3e-5
  warmup: 4000

model_name: T5
dataset_name: 'roszcz/maestro-v1-sustain'
target: denoise
seed: 26

overfit: False

tokens_per_note: multiple
time_quantization_method: start
masking_probability: 0.15
mask: notes

dataset:
  sequence_duration: 5
  sequence_step: 2

  quantization:
    start: 20
    duration: 5
    velocity: 5

device: "cuda:0"

log: True
log_frequency: 10
run_name: midi-T5-${now:%Y-%m-%d-%H-%M}
project: "midi-hf-transformer"

model:
  d_model: 512
  d_kv: 64
  d_ff: 2048
  num_layers: 6
  num_heads: 8
