train:
  num_epochs: 5
  accum_iter: 10
  batch_size: 8
  base_lr: 0.1
  warmup: 4000

model_name: T5
dataset_name: 'roszcz/maestro-v1-sustain'
target: velocity
seed: 26

overfit: False

time_quantization_method: start
dataset:
  sequence_duration: 5
  sequence_step: 2

  quantization:
    start: 400
    duration: 3
    velocity: 3

device: "cpu"

log: True
log_frequency: 10
run_name: midi-T5-${now:%Y-%m-%d-%H-%M}
project: "midi-hf-transformer"
